# Generated by Django 4.1.5 on 2023-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandInformations',
            fields=[
                ('username_primary_key', models.CharField(help_text='User name must be unique', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
