# Generated by Django 4.1.5 on 2023-10-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinformations',
            name='email',
        ),
    ]
