# Generated by Django 4.1.5 on 2023-10-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_remove_landinformations_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinformations',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='password',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='username_primary_key',
        ),
        migrations.AddField(
            model_name='landinformations',
            name='approval_status',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='block_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='district',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='land_coordinates',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='land_id',
            field=models.AutoField(default=' ', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='owner_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='plot_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='street_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='sub_division',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='survey_number',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='taluk',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='ward_number',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
