# Generated by Django 4.1.5 on 2023-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_remove_landinformations_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinformations',
            name='land_type',
            field=models.CharField(choices=[('Agricultural', 'Agricultural'), ('Private', 'Private'), ('Government', 'Government')], default='Agricultural', max_length=15),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='last_tax_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='patta_or_chitta_status',
            field=models.CharField(choices=[('Patta', 'Patta'), ('Chitta', 'Chitta')], default='Patta', max_length=10),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landinformations',
            name='urban_or_rural',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=10),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='approval_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='block_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='land_coordinates',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='land_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='plot_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='street_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='sub_division',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='survey_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='taluk',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landinformations',
            name='ward_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
