# Generated by Django 4.1.5 on 2023-10-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_landinformations_land_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landinformations',
            name='land_type',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='patta_or_chitta_status',
        ),
        migrations.RemoveField(
            model_name='landinformations',
            name='urban_or_rural',
        ),
    ]
